### ISSUE TITLE
Ability to update ZeroNet

### ISSUE THREAD

**Issue by TheMacMini09** [zeronetproxy/ZeroNetProxy#10]
Currently, the proxy is not up-to-date with the main ZeroNet repo. What is the best way to update it, and is it possible to automatically update it based on the current Git repo?

**Comment by shakna-israel** [comment]
Technically speaking, it should be able to automatically update, probably using rsync.

However, there are a couple differences between the proxy and the main branch, and those differences will grow as the projects develop. Simply because people use them differently.

I think the best tool for the job of automating a sync, but making sure the differences stay intact would be Grunt, but I'm not overly familiar with it.

**Comment by shakna-israel** [comment]
Current best thought:

Git pull from main ZeroNet.
Regex replace 127.0.0.1 in Config.py with reference to proxy config file.

**Comment by shakna-israel** [comment]
As of [631c8d50](https://github.com/zeronetproxy/ZeroNetProxy/commit/631c8d5051d03d7fe9b4c58ca886bafaaa984912) this should be fixed.

Run a git pull, and then re-run Proxify.
